name: Run Python

on:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Kiểm tra Python
        run: python --version

      - name: Chạy chương trình
        run: python gopcode.py
