name: Hello World

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Tôi đang đứng ở đâu?
        run: pwd

      - name: Trong thư mục có gì?
        run: ls -la

      - name: Tôi là ai?
        run: whoami

      - name: Hệ điều hành gì?
        run: uname -a
