name: Hello World

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:

      - name: Lấy source code
        uses: actions/checkout@v4

      - name: Liệt kê file
        run: ls -la

      - name: Đang ở đâu
        run: pwd
